BEGIN;

CREATE TABLE museum.media_assets (id uuid PRIMARY KEY, media_kind text NOT NULL CHECK (media_kind IN ('image','external_link','audio','video','document','iiif_manifest','model_3d')), usage_mode text NOT NULL CHECK (usage_mode IN ('bundled','remote','external_link')), license_status text NOT NULL CHECK (license_status IN ('verified','pending','rejected','unknown')), rights_status museum.rights_status NOT NULL, source_page_url text NOT NULL, original_url text, local_path text, creator text, institution text, license_name text NOT NULL, license_url text, attribution_zh text NOT NULL, attribution_en text NOT NULL, alt_text_zh text NOT NULL, alt_text_en text NOT NULL, retrieved_at date NOT NULL, checksum_sha256 text, width integer, height integer, duration_ms integer, CHECK (usage_mode <> 'bundled' OR (license_status = 'verified' AND checksum_sha256 IS NOT NULL)));
CREATE TABLE museum.media_links (media_id uuid NOT NULL REFERENCES museum.media_assets(id) ON DELETE CASCADE, entity_id uuid NOT NULL REFERENCES museum.entities(id) ON DELETE CASCADE, role text NOT NULL, sort_order integer NOT NULL, is_primary boolean NOT NULL DEFAULT false, crop_focus jsonb, PRIMARY KEY (media_id, entity_id, role));
CREATE TABLE museum.audio_profiles (media_id uuid PRIMARY KEY REFERENCES museum.media_assets(id) ON DELETE CASCADE, language_code text NOT NULL, reading_style text NOT NULL CHECK (reading_style IN ('spoken_reading','liturgical_recitation','chanting','reconstructed_reading','synthetic_reference')), reader_or_generator text NOT NULL, pronunciation_system text, transcript_entity_id uuid NOT NULL REFERENCES museum.entities(id), timing_track_path text, loudness_lufs numeric, generation_manifest_path text, editorial_note text);

CREATE TABLE museum.exhibitions (id uuid PRIMARY KEY, slug text NOT NULL UNIQUE, exhibition_kind text NOT NULL, publication_state museum.publication_state NOT NULL, review_status museum.review_status NOT NULL, default_locale text NOT NULL CHECK (default_locale IN ('zh-CN','en')), hero_media_id uuid REFERENCES museum.media_assets(id), estimated_quick_minutes integer NOT NULL CHECK (estimated_quick_minutes > 0), estimated_full_minutes integer NOT NULL CHECK (estimated_full_minutes >= estimated_quick_minutes), content_version text NOT NULL, CHECK (publication_state <> 'public' OR review_status = 'publishable'));
CREATE TABLE museum.exhibition_translations (exhibition_id uuid NOT NULL REFERENCES museum.exhibitions(id) ON DELETE CASCADE, locale text NOT NULL CHECK (locale IN ('zh-CN','en')), title text NOT NULL, subtitle text, curatorial_question text NOT NULL, opening_text text NOT NULL, closing_reflection text NOT NULL, source_note text NOT NULL, PRIMARY KEY (exhibition_id, locale));
CREATE TABLE museum.exhibition_sections (id uuid PRIMARY KEY, exhibition_id uuid NOT NULL REFERENCES museum.exhibitions(id) ON DELETE CASCADE, slug text NOT NULL, sequence integer NOT NULL, section_kind text NOT NULL, quick_tour_included boolean NOT NULL DEFAULT false, explore_state_snapshot jsonb, UNIQUE (exhibition_id, slug), UNIQUE (exhibition_id, sequence));
CREATE TABLE museum.exhibition_items (id uuid PRIMARY KEY, section_id uuid NOT NULL REFERENCES museum.exhibition_sections(id) ON DELETE CASCADE, entity_id uuid REFERENCES museum.entities(id), media_id uuid REFERENCES museum.media_assets(id), sequence integer NOT NULL, item_role text NOT NULL, curatorial_override_zh text, curatorial_override_en text, explore_state_snapshot jsonb, CHECK (entity_id IS NOT NULL OR media_id IS NOT NULL), UNIQUE (section_id, sequence));

COMMIT;
